FileVersion = 1
Projects = {t01Init = {Path = "tests/t01Init"}, CurlBeef = {Path = "deps/CurlBeef"}, BeefExtensionsLib = {Path = "deps/Beef-Extensions-Lib"}, JSON_Beef = {Path = "deps/JSON_Beef/lib"}, ari_core = {Path = "ari_core"}, test_core = {Path = "test_core"}, ari_2d = {Path = "ari_2d"}, ari_gfx = {Path = "ari_gfx"}, ari_en = {Path = "ari_en"}, ari_io = {Path = "ari_io"}, ari_net = {Path = "ari_net"}, ari_gui = {Path = "ari_gui"}, ari_3d = {Path = "ari_3d"}, ari_net_3d = {Path = "ari_net_3d"}}
ExtraPlatforms = ["armv7-none-linux-android21"]

[Workspace]
StartupProject = "t01Init"

[Configs.Test.Win32]
ConfigSelections = {t01Init = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {t01Init = {Config = "Debug"}}
